spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: joe
    password: Bigdata@123
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 9090
  servlet:
    context-path: /
